### ISSUE TITLE
Long strings error

### ISSUE THREAD

**Issue by JnthnWnbrg** [brenden/ukkonen-animation#1]
When building a suffix tree for tctcatcaa#ggaaccattg@tccatctcgc
There should be 3 leaves on the c->a->t branch because the "cat" substring occurs 3 times in the input string.

A visualization that works for this string is http://www.allisons.org/ll/AlgDS/Tree/Suffix/ 
But for the allisons.org visualization, you will need to input tctcatcaa#ggaaccattg@tccatctcgc$ with the dollar sign attached to get a more similar output because it does not automatically add a dollar sign.

**Comment by brenden** [comment]
Thanks for pointing that out. That issue should be fixed now.
